// <auto-generated />
using System;
using Lab_Assignment2_WhistPointCalculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab_Assignment2_WhistConsoleApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190410094931_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GamePlayers", b =>
                {
                    b.Property<int>("GamesId");

                    b.Property<int>("PlayerPosition")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId");

                    b.Property<int>("Points");

                    b.HasKey("GamesId", "PlayerPosition");

                    b.HasAlternateKey("PlayerPosition");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GameRoundPlayers", b =>
                {
                    b.Property<int>("PlayerPosition");

                    b.Property<int>("GameRoundsId");

                    b.Property<int>("Points");

                    b.HasKey("PlayerPosition");

                    b.HasIndex("GameRoundsId");

                    b.HasIndex("PlayerPosition", "Points");

                    b.ToTable("GameRoundPlayers");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GameRounds", b =>
                {
                    b.Property<int>("GameRoundsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DealerPosition");

                    b.Property<bool>("Ended");

                    b.Property<int>("GamesId");

                    b.Property<int>("RoundNumber");

                    b.Property<int>("RoundTypeId");

                    b.Property<bool>("Started");

                    b.HasKey("GameRoundsId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Games", b =>
                {
                    b.Property<int>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ended");

                    b.Property<int>("LocationId");

                    b.Property<string>("Name");

                    b.Property<bool>("Started");

                    b.Property<DateTime>("Updated");

                    b.HasKey("GamesId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Players", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Rounds", b =>
                {
                    b.Property<int>("GameRoundsId");

                    b.Property<int>("BidWinnerMatePositionId");

                    b.Property<int>("BidWinnerPositionId");

                    b.Property<int>("Tricks");

                    b.Property<int>("TricksWon");

                    b.Property<string>("Trump");

                    b.HasKey("GameRoundsId");

                    b.HasIndex("BidWinnerMatePositionId", "GameRoundsId")
                        .IsUnique();

                    b.HasIndex("BidWinnerPositionId", "GameRoundsId")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GamePlayers", b =>
                {
                    b.HasOne("Lab_Assignment2_WhistPointCalculator.Games", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lab_Assignment2_WhistPointCalculator.Players", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GameRoundPlayers", b =>
                {
                    b.HasOne("Lab_Assignment2_WhistPointCalculator.GameRounds", "GameRound")
                        .WithMany("GRPs")
                        .HasForeignKey("GameRoundsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lab_Assignment2_WhistPointCalculator.GamePlayers", "GamePlayer")
                        .WithMany("GRPs")
                        .HasForeignKey("PlayerPosition", "Points")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.GameRounds", b =>
                {
                    b.HasOne("Lab_Assignment2_WhistPointCalculator.Games", "Game")
                        .WithMany("GameRounds")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Location", b =>
                {
                    b.HasOne("Lab_Assignment2_WhistPointCalculator.Games", "Game")
                        .WithOne("Location")
                        .HasForeignKey("Lab_Assignment2_WhistPointCalculator.Location", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lab_Assignment2_WhistPointCalculator.Rounds", b =>
                {
                    b.HasOne("Lab_Assignment2_WhistPointCalculator.GameRounds", "Gameround")
                        .WithMany("Rounds")
                        .HasForeignKey("GameRoundsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lab_Assignment2_WhistPointCalculator.GamePlayers", "BidWinnerMateGameplayer")
                        .WithOne("WinnerMateNormalRound")
                        .HasForeignKey("Lab_Assignment2_WhistPointCalculator.Rounds", "BidWinnerMatePositionId", "GameRoundsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lab_Assignment2_WhistPointCalculator.GamePlayers", "BidWinnerGameplayer")
                        .WithOne("WinnerNormalRound")
                        .HasForeignKey("Lab_Assignment2_WhistPointCalculator.Rounds", "BidWinnerPositionId", "GameRoundsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
